apiVersion: v1
kind: Pod
metadata:
  name: mtu-test
spec:
  restartPolicy: Never
  nodeSelector:
    role: core
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "ping -c 3 -s 400 10.42.1.32 && echo SMALL-OK; ping -c 3 -s 1400 10.42.1.32 && echo LARGE-OK || echo LARGE-FAILED"]
