server:
  port: 8082

spring:
  application:
    name: program-service
  datasource:
    url: jdbc:postgresql://localhost:5433/eventdb
    username: eventapp
    password: changeme_local_dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
