apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
        role: analytics
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_FILE
              value: "/metabase-data/metabase.db"
            - name: JAVA_OPTS
              value: "-Xmx800m"
          resources:
            requests:
              memory: "700Mi"
              cpu: "200m"
            limits:
              memory: "1400Mi"
              cpu: "1"
          volumeMounts:
            - name: metabase-storage
              mountPath: /metabase-data
      volumes:
        - name: metabase-storage
          persistentVolumeClaim:
            claimName: metabase-data
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300